version: '3.7'

services:
  bot:
    build:
      context: .
    restart: always
    stop_signal: SIGINT
    depends_on:
      - redis
      - postgres
    environment:
      BOT_PUBLIC_PORT: 80
      BOT_TOKEN:
      ADMIN_ID:
      CHEF_ID:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:

  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:12-alpine
    restart: on-failure
    shm_size: 128mb
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:

volumes:
  redis-data:
  postgres-data:
  init_db:
